# Generated by Django 2.0.8 on 2019-01-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_skill', models.CharField(max_length=20, null=True)),
                ('active_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityInEq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20, null=True)),
                ('ability', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ManyToManyField(blank=True, to='posteq.AbilityInEq')),
            ],
        ),
        migrations.CreateModel(
            name='DataOfEq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[('共', '共用'), ('男', '男性用'), ('女', '女性用')], max_length=1)),
                ('job', models.CharField(choices=[('共用', '共用'), ('ガンナー', 'ガンナー用'), ('剣士', '剣士用')], max_length=4)),
                ('slot', models.IntegerField(default=0)),
                ('rare', models.IntegerField(default=0)),
                ('Class', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elemental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire', models.IntegerField(default=0)),
                ('watr', models.IntegerField(default=0)),
                ('thnd', models.IntegerField(default=0)),
                ('drgn', models.IntegerField(default=0)),
                ('ice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_date', models.DateTimeField(null=True, verbose_name='投稿日時')),
                ('good', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EqActiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20, null=True)),
                ('ability', models.ManyToManyField(blank=True, to='posteq.AbilityInEq')),
                ('data', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq')),
                ('element', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.Elemental')),
            ],
        ),
        migrations.CreateModel(
            name='EqSkillPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JewelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ManyToManyField(blank=True, to='posteq.AbilityInEq')),
                ('data', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq')),
            ],
        ),
        migrations.CreateModel(
            name='SkillBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('skillrank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_skill', models.CharField(max_length=20, null=True)),
                ('active_point', models.IntegerField(default=0)),
                ('contain', models.ManyToManyField(blank=True, related_name='contained_in', to='posteq.SkillDetail')),
                ('deactive', models.ManyToManyField(blank=True, related_name='deactive_by', to='posteq.SkillDetail')),
            ],
        ),
        migrations.CreateModel(
            name='SkillInEq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20, null=True)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TagBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeniSkillBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('active_abilities', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.AbilityDetail')),
            ],
        ),
        migrations.CreateModel(
            name='WepKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('short_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='skillbase',
            name='active_skills',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.SkillDetail'),
        ),
        migrations.AddField(
            model_name='jeweldata',
            name='skills',
            field=models.ManyToManyField(blank=True, to='posteq.SkillInEq'),
        ),
        migrations.AddField(
            model_name='eqdata',
            name='skills',
            field=models.ManyToManyField(blank=True, to='posteq.SkillInEq'),
        ),
        migrations.AddField(
            model_name='eq',
            name='active_skills',
            field=models.ManyToManyField(blank=True, related_name='active_skills_in_eq', to='posteq.EqActiveSkill'),
        ),
        migrations.AddField(
            model_name='eq',
            name='active_teni_skills',
            field=models.ManyToManyField(blank=True, related_name='active_teni_skills_in_eq', to='posteq.EqActiveSkill'),
        ),
        migrations.AddField(
            model_name='eq',
            name='arm_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arm_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='body_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='cuff_data',
            field=models.ManyToManyField(blank=True, to='posteq.CuffData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='deactive_skills',
            field=models.ManyToManyField(blank=True, related_name='deactive_skills_in_eq', to='posteq.EqActiveSkill'),
        ),
        migrations.AddField(
            model_name='eq',
            name='head_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='jewel_data',
            field=models.ManyToManyField(blank=True, to='posteq.JewelData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='leg_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leg_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='passive_skills',
            field=models.ManyToManyField(blank=True, related_name='passive_skills_in_eq', to='posteq.EqActiveSkill'),
        ),
        migrations.AddField(
            model_name='eq',
            name='skill_points',
            field=models.ManyToManyField(blank=True, related_name='skill_points_in_eq', to='posteq.EqSkillPoint'),
        ),
        migrations.AddField(
            model_name='eq',
            name='skill_teni_points',
            field=models.ManyToManyField(blank=True, related_name='skill_teni_points_in_eq', to='posteq.EqSkillPoint'),
        ),
        migrations.AddField(
            model_name='eq',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='posteq.TagBase'),
        ),
        migrations.AddField(
            model_name='eq',
            name='wep_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wep_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='eq',
            name='wep_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.WepKind'),
        ),
        migrations.AddField(
            model_name='eq',
            name='wst_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wst_in_eq', to='posteq.EqData'),
        ),
        migrations.AddField(
            model_name='cuffdata',
            name='data',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq'),
        ),
        migrations.AddField(
            model_name='cuffdata',
            name='skills',
            field=models.ManyToManyField(blank=True, to='posteq.SkillInEq'),
        ),
    ]
