# Generated by Django 2.0.8 on 2019-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataofeq',
            name='Class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='job',
            field=models.CharField(blank=True, choices=[('共用', '共用'), ('ガンナー', 'ガンナー用'), ('剣士', '剣士用')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='sex',
            field=models.CharField(blank=True, choices=[('共', '共用'), ('男', '男性用'), ('女', '女性用')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posteq.TagBase'),
        ),
    ]
