# Generated by Django 2.0.8 on 2019-01-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0003_auto_20190129_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilityineq',
            name='num',
        ),
        migrations.RemoveField(
            model_name='skillineq',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skillineq',
            name='num',
        ),
        migrations.AddField(
            model_name='skillineq',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.SkillBase'),
        ),
        migrations.RemoveField(
            model_name='skillbase',
            name='active_skills',
        ),
        migrations.AddField(
            model_name='skillbase',
            name='active_skills',
            field=models.ManyToManyField(blank=True, to='posteq.SkillDetail'),
        ),
    ]
