# Generated by Django 2.0.8 on 2019-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0004_auto_20190129_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillbase',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
