# Generated by Django 2.1.5 on 2019-02-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0005_skillbase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeweldata',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq'),
        ),
    ]
