# Generated by Django 2.1.5 on 2019-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0006_auto_20190211_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teniskillbase',
            name='active_abilities',
        ),
        migrations.AddField(
            model_name='teniskillbase',
            name='active_abilities',
            field=models.ManyToManyField(blank=True, to='posteq.AbilityDetail'),
        ),
    ]
