# Generated by Django 2.1.5 on 2019-02-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0007_auto_20190228_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='WepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ManyToManyField(blank=True, to='posteq.AbilityInEq')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq')),
                ('skills', models.ManyToManyField(blank=True, to='posteq.SkillInEq')),
            ],
        ),
        migrations.AlterField(
            model_name='cuffdata',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posteq.DataOfEq'),
        ),
        migrations.AlterField(
            model_name='eq',
            name='wep_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wep_in_eq', to='posteq.WepData'),
        ),
    ]
