# Generated by Django 2.1.5 on 2019-04-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0010_auto_20190331_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuffsInEq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('Cuff_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.CuffData')),
            ],
        ),
        migrations.CreateModel(
            name='JewelsInEq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('Jewel_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.JewelData')),
            ],
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='job',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='dataofeq',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='eq',
            name='cuff_data',
            field=models.ManyToManyField(blank=True, to='posteq.CuffsInEq'),
        ),
        migrations.AlterField(
            model_name='eq',
            name='jewel_data',
            field=models.ManyToManyField(blank=True, to='posteq.JewelsInEq'),
        ),
    ]
