# Generated by Django 2.1.5 on 2019-04-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('posteq', '0012_auto_20190401_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq',
            name='posted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postedeqs', to='user.User'),
        ),
        migrations.AddField(
            model_name='eq',
            name='saved_user',
            field=models.ManyToManyField(blank=True, related_name='savedeqs', to='user.User'),
        ),
    ]
