# Generated by Django 2.1.5 on 2019-04-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0013_auto_20190401_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq',
            name='posted_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
