# Generated by Django 2.1.5 on 2019-04-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0015_updatehist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqdata',
            name='part',
        ),
        migrations.AddField(
            model_name='dataofeq',
            name='part',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eqdata',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.DataOfEq'),
        ),
        migrations.AlterField(
            model_name='eqdata',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.Elemental'),
        ),
        migrations.AlterField(
            model_name='wepdata',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posteq.DataOfEq'),
        ),
    ]
