# Generated by Django 2.1.5 on 2019-04-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('self_introduce', models.CharField(max_length=400, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('access_token_secret', models.CharField(blank=True, max_length=100)),
                ('Url', models.URLField(blank=True)),
                ('UrlTitle', models.CharField(blank=True, max_length=100)),
                ('UrlDescription', models.CharField(blank=True, max_length=400)),
                ('UrlIfChecked', models.BooleanField(blank=True, null=True)),
                ('UrlAlertForAdmin', models.BooleanField(default=False)),
                ('follow', models.ManyToManyField(blank=True, related_name='followed', to='user.User', verbose_name='フォロー')),
            ],
        ),
    ]
