# Generated by Django 2.1.5 on 2019-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190403_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_introduce',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
