# Generated by Django 2.1.5 on 2019-05-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posteq', '0016_auto_20190404_2023'),
        ('user', '0003_auto_20190428_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possess_cuff', models.ManyToManyField(blank=True, to='posteq.CuffData')),
                ('possess_equip', models.ManyToManyField(blank=True, to='posteq.EqData')),
                ('possess_jewel', models.ManyToManyField(blank=True, to='posteq.JewelData')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='possess_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.PossessItem'),
        ),
    ]
